site_name: 'Monarch KG Tools'
repo_name: 'monarch-app/backend'
repo_url: 'https://github.com/monarch-initiative/monarch-app/tree/main/backend'
site_url: 'https://monarch-app.monarchinitiative.org/docs/'


nav:
  - monarch-py:
    - Overview: 'index.md'
    - Usage: 'Usage/index.md'
    - CLI: 'Usage/CLI.md'
    - Data Model: 'Data-Model/index.md'
    - Interfaces: 
      - Overview: 'Usage/Interfaces/index.md'
      - Entity: 'Usage/Interfaces/Entity.md'
      - Association: 'Usage/Interfaces/Association.md'
      - Query: 'Usage/Interfaces/Query.md'
      - Search: 'Usage/Interfaces/Search.md'
    - Implementations: 
      - Overview: 'Usage/Implementations/index.md'
      - Solr: 'Usage/Implementations/Solr.md'
      - SQL: 'Usage/Implementations/SQL.md'
      # - OAK: 'Usage/Implementations/OAK.md'
  - Release Process: 'release-process.md'
  - FastAPI: 
    - Overview: 'FastAPI/index.md'
    - Endpoints: 
      - 'FastAPI/Endpoints/index.md'


theme:
  name: 'material'
  docs_dir: docs/
  logo: 'images/monarch-initiative.png'
  favicon: 'images/favicon.ico'
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: 'Source Sans Pro'
    code: 'Source Sans Pro Mono'


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [./backend]
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/objects.inv
            - https://mkdocstrings.github.io/griffe/objects.inv
          options:
            docstring_style: google
            docstring_options:
              docstring_section_style: table
              ignore_init_summary: yes
            merge_init_into_class: yes
            # separate_signature: yes
            show_signature: no
            show_source: no
            show_root_full_path: no
            show_root_toc_entry: False
            filters:
              - '!^_[^_]'
              # - '^_[^_]'


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true


extra:
  social:
    - icon: 'fontawesome/solid/house'
      link: 'https://monarchinitiative.org'
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/monarch-initiative/'


