name: Deploy Frontend

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./frontend

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install packages
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: true
          folder: frontend/dist
          clean-exclude: docs
