name: Test Backend

on:
  pull_request:
  workflow_dispatch:

# defaults:
#   run:
#     working-directory: ./backend

jobs:
  test-backend:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest]
        #os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      #----------------------------------------------
      #          install & configure poetry
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1

      #----------------------------------------------
      #    install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: poetry -C backend install --no-interaction

      #----------------------------------------------
      #              run pytest
      #----------------------------------------------
      - name: Run tests
        run: poetry -C backend run pytest backend/tests

      #----------------------------------------------
      #              coverage report
      #----------------------------------------------
      - name: Generate coverage results
        run: |
          poetry -C backend run coverage run -m pytest backend/tests
          poetry run coverage xml
          poetry run coverage report -m
        shell: bash

